//@ sourceMappingURL=songlocator-cli.map
// Generated by CoffeeScript 1.6.1
/*

  Command line interface for SongLocator.

  2013 (c) Andrey Popp <8mayday@gmail.com>
*/

var ResolverSet, rankSearchResults, readFileSync, _ref;

readFileSync = require('fs').readFileSync;

_ref = require('songlocator-base'), ResolverSet = _ref.ResolverSet, rankSearchResults = _ref.rankSearchResults;

exports.readConfigSync = function(filename) {
  if (filename == null) {
    filename = './songlocator.json';
  }
  try {
    return JSON.parse(readFileSync(filename));
  } catch (e) {
    return void 0;
  }
};

exports.parseArguments = function(argv) {
  var arg, args, opts;
  if (argv == null) {
    argv = process.argv;
  }
  argv = argv.splice(2);
  args = [];
  opts = {
    config: void 0,
    resolvers: [],
    debug: false
  };
  while (argv.length > 0) {
    arg = argv.shift();
    if (arg === '-c' || arg === '--config') {
      opts.config = argv.shift();
    } else if (arg === '--debug') {
      opts.debug = true;
    } else if (arg.substring(0, 6) === '--use-') {
      opts.resolvers.push(arg.substring(6));
    } else {
      args.push(arg);
    }
  }
  return {
    args: args,
    opts: opts
  };
};
